## <font color = '#7FFFD4'> What are pandas?

**Pandas** is a Python library used to manipulate data sets.

It offers data cleaning, exploration and analysis.

### <font color = '#DEB887'> Import Pandas

In [1]:
# import pandas using alias
import pandas as pd

# alternatively
# from pandas import *

### <font color = '#DEB887'>  DataFrames

\
Data sets in Pandas are generally multidimensional arrays, known as data frames.

In [32]:
# data = dict()
data = {
        "calories": [420, 390, 390, 389, 340, 350, 342, 560, 340, 490],
        "duration": [50, 40, 40, 45, 56, 39,50, 51, 42, 43]
       }

# dataframe
df_data = pd.DataFrame(data)

df_data

   calories  duration
0       420        50
1       390        40
2       390        40
3       389        45
4       340        56
5       350        39
6       342        50
7       560        51
8       340        42
9       490        43

####  <font color = '#FF7F50'> Show data using the loc and iloc functions

In [33]:
df_data.loc[0,"calories"]

420

In [34]:
df_data.iloc[0,0]

420

In [35]:
# display first two rows using loc
df_data.loc[0:1,:]

   calories  duration
0       420        50
1       390        40

In [36]:
# display first two rows using iloc
df_data.iloc[0:2,:]

   calories  duration
0       420        50
1       390        40

In [37]:
# display the first 5 rows through calories and duration
df_data.loc[:4, "calories":"duration"]

   calories  duration
0       420        50
1       390        40
2       390        40
3       389        45
4       340        56

In [38]:
df_data.iloc[:5, [0,1]]

   calories  duration
0       420        50
1       390        40
2       390        40
3       389        45
4       340        56

####  <font color = '#FF7F50'> Show data using the head and tail functions

In [39]:
# display the first 3 rows using head function
df_data.head(3)

   calories  duration
0       420        50
1       390        40
2       390        40

In [40]:
# display the last 2 rows using tail function
df_data.tail(2)

   calories  duration
8       340        42
9       490        43

### <font color = '#DEB887'>  Charger des fichiers données dans un DataFrame

In [41]:
# import data from a csv file
df_data_csv = pd.read_csv("/home/students-aimssn/Documents/Data collection/DC 1-20251117T174511Z-1-001/DC 1/DC 1/DCP 1/data.csv")

df_data_csv.head()

   calories  duration        date
0     420.0      50.0  2022/05/05
1     390.0      40.0  2022/05/06
2     390.0      40.0  2022/05/06
3     389.0      45.0  2022/05/07
4     340.0      56.0  2022/05/08

In [42]:
# import data from a csv excel
df_data_excel = pd.read_excel("data.xlsx")

df_data_excel.head()

   Unnamed: 0  calories  duration
0           0       420        50
1           1       390        40
2           2       390        40
3           3       389        45
4           4       340        56

In [43]:
# show the dimension of the data
df_data_csv.shape

(12, 3)

In [44]:
# show the list of column names 
df_data_csv.columns

Index(['calories', 'duration', 'date'], dtype='object')

In [45]:
# rename column names
df_data_csv.rename(columns = {"calories": "Calories(cal)", "duration": "Duration(sec)", "date": "Date(yyyy/mm/dd)"})

# alternatively
# df_data_csv.columns = ["Calories(cal)", "Duration(sec)", "Date"]

    Calories(cal)  Duration(sec) Date(yyyy/mm/dd)
0           420.0           50.0       2022/05/05
1           390.0           40.0       2022/05/06
2           390.0           40.0       2022/05/06
3           389.0           45.0       2022/05/07
4           340.0           56.0       2022/05/08
5           350.0           39.0       2022/05/09
6           342.0           50.0       2022/05/02
7           560.0           51.0       2022/05/03
8           340.0           42.0       2022/05/10
9           490.0           43.0       2022/05/11
10            NaN           45.0       2022/05/12
11          450.0            NaN       2022/05/14

In [49]:
# show indexes 
df_data_csv.index

RangeIndex(start=0, stop=12, step=1)

In [50]:
# alternatively
df_data_csv.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
# change the indexes
df_data_csv.rename(index = {0:1, 1:2, 2:3, 3:4, 4:5, 5:6, 6:7, 7:8, 8:9, 9:10, 10:11, 11:12})

# alternatively
#for i in range(len(df_data_csv)):
#    df_data_csv.rename(index = {i: "day" + str(i)}, inplace = True)
    
#df_data_csv

    calories  duration        date
1      420.0      50.0  2022/05/05
2      390.0      40.0  2022/05/06
3      390.0      40.0  2022/05/06
4      389.0      45.0  2022/05/07
5      340.0      56.0  2022/05/08
6      350.0      39.0  2022/05/09
7      342.0      50.0  2022/05/02
8      560.0      51.0  2022/05/03
9      340.0      42.0  2022/05/10
10     490.0      43.0  2022/05/11
11       NaN      45.0  2022/05/12
12     450.0       NaN  2022/05/14

In [53]:
# Describe the data (by default, it includes only numerical data)
df_data_csv.describe()

         calories   duration
count   11.000000  11.000000
mean   405.545455  45.545455
std     70.460434   5.502066
min    340.000000  39.000000
25%    346.000000  41.000000
50%    390.000000  45.000000
75%    435.000000  50.000000
max    560.000000  56.000000

In [56]:
# categorial data 
df_data_csv.describe(include = "object")

              date
count           12
unique          11
top     2022/05/06
freq             2

In [58]:
# both numerical data and categorical data
df_data_csv.describe(include = "all")

          calories   duration        date
count    11.000000  11.000000          12
unique         NaN        NaN          11
top            NaN        NaN  2022/05/06
freq           NaN        NaN           2
mean    405.545455  45.545455         NaN
std      70.460434   5.502066         NaN
min     340.000000  39.000000         NaN
25%     346.000000  41.000000         NaN
50%     390.000000  45.000000         NaN
75%     435.000000  50.000000         NaN
max     560.000000  56.000000         NaN

In [59]:
# Infos of the data
df_data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calories  11 non-null     float64
 1   duration  11 non-null     float64
 2   date      12 non-null     object
dtypes: float64(2), object(1)
memory usage: 416.0+ bytes

### <font color = '#DEB887'> Pandas - Data Cleaning

In [60]:
# import data.csv
df = pd.read_csv("data.csv")

df

    calories  duration        date
0      420.0      50.0  2022/05/05
1      390.0      40.0  2022/05/06
2      390.0      40.0  2022/05/06
3      389.0      45.0  2022/05/07
4      340.0      56.0  2022/05/08
5      350.0      39.0  2022/05/09
6      342.0      50.0  2022/05/02
7      560.0      51.0  2022/05/03
8      340.0      42.0  2022/05/10
9      490.0      43.0  2022/05/11
10       NaN      45.0  2022/05/12
11     450.0       NaN  2022/05/14

In [61]:
# Check the existence of null values 
df.isnull()

    calories  duration   date
0      False     False  False
1      False     False  False
2      False     False  False
3      False     False  False
4      False     False  False
5      False     False  False
6      False     False  False
7      False     False  False
8      False     False  False
9      False     False  False
10      True     False  False
11     False      True  False

In [70]:
# Using 'sum' funtion (counts the number of missing variables  in each column)
df.isnull().sum()

calories    1
duration    1
date        0
dtype: int64

In [71]:
# Using 'any' funtion (counts the number of columns with missing variables)
df.isnull().any().sum()

2

In [73]:
# using 'isna' function
df.isna().sum()

calories    1
duration    1
date        0
dtype: int64

In [82]:
# Delete null values using dropna 
df.dropna(inplace = True)

df

   calories  duration        date
0     420.0      50.0  2022/05/05
1     390.0      40.0  2022/05/06
2     390.0      40.0  2022/05/06
3     389.0      45.0  2022/05/07
4     340.0      56.0  2022/05/08
5     350.0      39.0  2022/05/09
6     342.0      50.0  2022/05/02
7     560.0      51.0  2022/05/03
8     340.0      42.0  2022/05/10
9     490.0      43.0  2022/05/11

#### NOTE: It is important to know the distribution of data before cleaning

In [93]:
# import data.csv
df = pd.read_csv("data.csv")

df

    calories  duration        date
0      420.0      50.0  2022/05/05
1      390.0      40.0  2022/05/06
2      390.0      40.0  2022/05/06
3      389.0      45.0  2022/05/07
4      340.0      56.0  2022/05/08
5      350.0      39.0  2022/05/09
6      342.0      50.0  2022/05/02
7      560.0      51.0  2022/05/03
8      340.0      42.0  2022/05/10
9      490.0      43.0  2022/05/11
10       NaN      45.0  2022/05/12
11     450.0       NaN  2022/05/14

In [94]:
# Replace null values by the mean (for numeric variables (when data is symmetric))
for col in df.columns[:2]:
    df[col].fillna(df[col].mean(), inplace = True)
    
df

      calories   duration        date
0   420.000000  50.000000  2022/05/05
1   390.000000  40.000000  2022/05/06
2   390.000000  40.000000  2022/05/06
3   389.000000  45.000000  2022/05/07
4   340.000000  56.000000  2022/05/08
5   350.000000  39.000000  2022/05/09
6   342.000000  50.000000  2022/05/02
7   560.000000  51.000000  2022/05/03
8   340.000000  42.000000  2022/05/10
9   490.000000  43.000000  2022/05/11
10  405.545455  45.000000  2022/05/12
11  450.000000  45.545455  2022/05/14

In [96]:
# import data.csv
df = pd.read_csv("data.csv")

df

    calories  duration        date
0      420.0      50.0  2022/05/05
1      390.0      40.0  2022/05/06
2      390.0      40.0  2022/05/06
3      389.0      45.0  2022/05/07
4      340.0      56.0  2022/05/08
5      350.0      39.0  2022/05/09
6      342.0      50.0  2022/05/02
7      560.0      51.0  2022/05/03
8      340.0      42.0  2022/05/10
9      490.0      43.0  2022/05/11
10       NaN      45.0  2022/05/12
11     450.0       NaN  2022/05/14

In [97]:
# Replace null values by the median (for numerical variables (when data is skewed))
for col in df.columns[:2]:
    df[col].fillna(df[col].median(), inplace = True)
    
df

    calories  duration        date
0      420.0      50.0  2022/05/05
1      390.0      40.0  2022/05/06
2      390.0      40.0  2022/05/06
3      389.0      45.0  2022/05/07
4      340.0      56.0  2022/05/08
5      350.0      39.0  2022/05/09
6      342.0      50.0  2022/05/02
7      560.0      51.0  2022/05/03
8      340.0      42.0  2022/05/10
9      490.0      43.0  2022/05/11
10     390.0      45.0  2022/05/12
11     450.0      45.0  2022/05/14

In [98]:
# import data.csv
df = pd.read_csv("data.csv")

df

    calories  duration        date
0      420.0      50.0  2022/05/05
1      390.0      40.0  2022/05/06
2      390.0      40.0  2022/05/06
3      389.0      45.0  2022/05/07
4      340.0      56.0  2022/05/08
5      350.0      39.0  2022/05/09
6      342.0      50.0  2022/05/02
7      560.0      51.0  2022/05/03
8      340.0      42.0  2022/05/10
9      490.0      43.0  2022/05/11
10       NaN      45.0  2022/05/12
11     450.0       NaN  2022/05/14

In [101]:
# Replace null values by the mode (for categorical and numerical variables)
for col in df.columns[:2]:
    df[col].fillna(df[col].mode()[0], inplace = True)
    
df

    calories  duration        date
0      420.0      50.0  2022/05/05
1      390.0      40.0  2022/05/06
2      390.0      40.0  2022/05/06
3      389.0      45.0  2022/05/07
4      340.0      56.0  2022/05/08
5      350.0      39.0  2022/05/09
6      342.0      50.0  2022/05/02
7      560.0      51.0  2022/05/03
8      340.0      42.0  2022/05/10
9      490.0      43.0  2022/05/11
10     340.0      45.0  2022/05/12
11     450.0      40.0  2022/05/14

In [102]:
# import data.csv
df = pd.read_csv("data.csv")

df

    calories  duration        date
0      420.0      50.0  2022/05/05
1      390.0      40.0  2022/05/06
2      390.0      40.0  2022/05/06
3      389.0      45.0  2022/05/07
4      340.0      56.0  2022/05/08
5      350.0      39.0  2022/05/09
6      342.0      50.0  2022/05/02
7      560.0      51.0  2022/05/03
8      340.0      42.0  2022/05/10
9      490.0      43.0  2022/05/11
10       NaN      45.0  2022/05/12
11     450.0       NaN  2022/05/14

In [105]:
# Check the types of the different variables 
df.dtypes

calories    float64
duration    float64
date         object
dtype: object

In [120]:
# import data1.csv
df = pd.read_csv("data1.csv")

df

      calories   duration        date
0   420.000000  50.000000  2022/05/05
1   390.000000  40.000000  2022/05/06
2   390.000000  40.000000  2022/05/06
3   389.000000  45.000000  2022/05/07
4   340.000000  56.000000  2022/05/08
5   350.000000  39.000000  2022/05/09
6   342.000000  50.000000  2022/05/02
7   560.000000  51.000000  2022/05/03
8   340.000000  42.000000  2022/05/10
9   490.000000  43.000000  2022/05/11
10  405.545455  45.000000  2022/05/12
11  450.000000  45.545455  2022/05/14

In [121]:
# Convert calories in integer using astype 
df.calories = df.calories.astype("int64")

df.dtypes

calories      int64
duration    float64
date         object
dtype: object

In [122]:
# convert data in datetime64 using astype 
df.date = df.date.astype("datetime64[ns]")

df.dtypes

calories             int64
duration           float64
date        datetime64[ns]
dtype: object

In [123]:
# Delete rows (axis = 0) 
df.drop([0,1], axis = 0, inplace = True )

df

    calories   duration       date
2        390  40.000000 2022-05-06
3        389  45.000000 2022-05-07
4        340  56.000000 2022-05-08
5        350  39.000000 2022-05-09
6        342  50.000000 2022-05-02
7        560  51.000000 2022-05-03
8        340  42.000000 2022-05-10
9        490  43.000000 2022-05-11
10       405  45.000000 2022-05-12
11       450  45.545455 2022-05-14

In [126]:
# Delete columns (axis = 1)
df.drop(["duration"], axis = 1, inplace = True )

df

    calories       date
2        390 2022-05-06
3        389 2022-05-07
4        340 2022-05-08
5        350 2022-05-09
6        342 2022-05-02
7        560 2022-05-03
8        340 2022-05-10
9        490 2022-05-11
10       405 2022-05-12
11       450 2022-05-14

In [127]:
# import data2.csv
df = pd.read_csv("data2.csv")

df

    calories  duration        date
0        420        50  2022-05-05
1        390        40  2022-05-06
2        390        40  2022-05-06
3        389        45  2022-05-07
4        340        56  2022-05-08
5        350        39  2022-05-09
6        342        50  2022-05-02
7        560        51  2022-05-03
8        340        42  2022-05-10
9        490        43  2022-05-11
10       450        45  2022-05-12

In [128]:
# Check the existence of duplicates 
df.duplicated().sum()

1

In [129]:
# Delete duplicates 
df.drop_duplicates(inplace = True)

df

    calories  duration        date
0        420        50  2022-05-05
1        390        40  2022-05-06
3        389        45  2022-05-07
4        340        56  2022-05-08
5        350        39  2022-05-09
6        342        50  2022-05-02
7        560        51  2022-05-03
8        340        42  2022-05-10
9        490        43  2022-05-11
10       450        45  2022-05-12

In [130]:
df.duplicated().sum()

0

In [135]:
# Download the data
df.to_csv("clean_data_csv", index = False)